<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="63" started-at="2020-01-28T09:40:00Z" finished-at="2020-01-28T09:40:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="63" started-at="2020-01-28T09:40:00Z" finished-at="2020-01-28T09:40:00Z">
      <class name="framework.Test1">
        <test-method status="PASS" signature="config()[pri:0, instance:framework.Test1@27efef64]" name="config" is-config="true" duration-ms="782" started-at="2020-01-28T15:09:59Z" finished-at="2020-01-28T15:10:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config -->
        <test-method status="FAIL" signature="getTest()[pri:0, instance:framework.Test1@27efef64]" name="getTest" duration-ms="31" started-at="2020-01-28T15:10:00Z" finished-at="2020-01-28T15:10:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at framework.ApiMethod.executeRequest(ApiMethod.java:17)
	at framework.Test1.getTest(Test1.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTest -->
        <test-method status="PASS" signature="postTest()[pri:0, instance:framework.Test1@27efef64]" name="postTest" duration-ms="0" started-at="2020-01-28T15:10:00Z" finished-at="2020-01-28T15:10:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postTest -->
      </class> <!-- framework.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
